// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StarbucksApi.DataAccessLayer;

namespace StarbucksApi.Migrations
{
    [DbContext(typeof(StarbucksCoffeeDbContext))]
    [Migration("20230108205521_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("CharacteristicCoffee", b =>
                {
                    b.Property<int>("CharacteristicsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CoffeesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CharacteristicsId", "CoffeesId");

                    b.HasIndex("CoffeesId");

                    b.ToTable("CharacteristicCoffee");

                    b.HasData(
                        new
                        {
                            CharacteristicsId = 1,
                            CoffeesId = 1
                        },
                        new
                        {
                            CharacteristicsId = 2,
                            CoffeesId = 1
                        },
                        new
                        {
                            CharacteristicsId = 2,
                            CoffeesId = 2
                        },
                        new
                        {
                            CharacteristicsId = 3,
                            CoffeesId = 2
                        },
                        new
                        {
                            CharacteristicsId = 3,
                            CoffeesId = 3
                        });
                });

            modelBuilder.Entity("StarbucksApi.DataAccessLayer.Entities.Characteristic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Characteristics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "extra cream"
                        },
                        new
                        {
                            Id = 2,
                            Description = "brown sugar"
                        },
                        new
                        {
                            Id = 3,
                            Description = "double shot"
                        });
                });

            modelBuilder.Entity("StarbucksApi.DataAccessLayer.Entities.Coffee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Coffeees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Type = "Starbucks Latte"
                        },
                        new
                        {
                            Id = 2,
                            Type = "Starbucks Macchiato"
                        },
                        new
                        {
                            Id = 3,
                            Type = "Starbucks Espresso"
                        });
                });

            modelBuilder.Entity("CharacteristicCoffee", b =>
                {
                    b.HasOne("StarbucksApi.DataAccessLayer.Entities.Characteristic", null)
                        .WithMany()
                        .HasForeignKey("CharacteristicsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarbucksApi.DataAccessLayer.Entities.Coffee", null)
                        .WithMany()
                        .HasForeignKey("CoffeesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
